### ISSUE TITLE
Add commit and push to git repositories

### ISSUE THREAD

**Issue by daniellanner** [daniellanner/snowfs-for-unity#15]
# Add collaboration features for established version control tools

After local iterations the user may want to easily push his changes to a git repo or p4 repo.

- SnowFS for Unity version 0.9.1

## Description

While SnowFS is primarily a tool for artists to increase their iteration time with local commits, the user is still part of a team and will eventually have to push the changes to a remote location.

While there are many helper tools for git and p4 (also already integrated in Unity), some of them are a little to verbose and offer too much functionality to cover the use cases of various roles. We can add a simple commit and push functionality for git and p4 to the plugin. 

## Current workarounds

Currently the user would push and pull via console, git tools or p4 helix.

## Tasks

- [ ] Ensure the request title follows contribution rules
- [ ] Delete non-applicable description
- [ ] I would like to work on this feature
