### ISSUE TITLE
Initializing the repository is an opaque and slow process

### ISSUE THREAD

**Issue by daniellanner** [daniellanner/snowfs-for-unity#19]
# Improve SnowFS for Unity onboarding

*SnowFS for Unity* would benefit from a **Getting things started** window.

- Unity version 2020.3.14f1
- SnowFS for Unity version v0.9.1

## Description

Given how in some larger projects the initial `snow status` can take up to a minute on older HDD discs and may be redundant due to potential files that can be ignored, the onboarding of the plugin should be improved. 

## Proposed Solution

When setting up the plugin the user should have the option of adding files to the ignore list and read some helpful advice for the plugin while it is starting things uo in the background.

### As done by

Most software packages have this process. For an example solution see [Snowtrack](https://snowtrack.io/) (shameful plug of the product that birthed *SnowFS*).

## Current workarounds

Currently the user has to wait without feedback for the window to update and then re-focus on the window for triggering `snow log` and `snow status`.

## Tasks

- [x] Ensure the request title follows contribution rules
- [x] Delete non-applicable description
- [x] I would like to work on this feature
