### ISSUE TITLE
:star: Show changed files of version in History panel

### ISSUE THREAD

**Issue by daniellanner** [daniellanner/snowfs-for-unity#2]
# Show changed files in history

Currently there is a non-functioning debug preview of which files changed when hovering over a version in the history panel. 

- SnowFS for Unity v0.9.1

## Description

Usually version control tools have a diff view of files. While this may be out of scope for the moment, some low hanging fruit is to show which files changed with which version. This increases readability of versions and helps organize my work.

## Proposed Solution

When hovering over show the changed files. Also list them when expanding a version in the history panel.

### As done by

When inspecting commits on Github we receive a list of changed items. See the [initial commit of this repository](https://github.com/daniellanner/snowfs-for-unity/commit/865faeb4d1a2a5e252e76fa7ca7cb18ab550e203).

## Tasks

- [ ] Ensure the request title follows contribution rules
- [ ] Delete non-applicable description
- [ ] I would like to work on this feature

**Comment by daniellanner** [comment]
Feature currently in development in [SnowFS](https://github.com/Snowtrack/SnowFS). ⌚
