### ISSUE TITLE
Initializing repository on macOS does nothing

### ISSUE THREAD

**Issue by daniellanner** [daniellanner/snowfs-for-unity#4]
# Initializing repository on macOS does nothing

Initializing a repository does not work on macOS.

- Unity 2020.3.7f1
- SnowFS for Unity v0.9.1

## Description

When clicking the *Initialize* button in the SnowFS for Window window nothing happens. The editor does not crash and there is no error message and no `.snow` repository is being created. A `.snowignore` file has been created at the `Assets` root.

### Expected behavior

Clicking the *Initialize* button should create a `.snow` repository at the `Assets` root.

## To Reproduce

1. Open *Window/SnowFS for Unity*
2. Click on *Initialize*
3. Nothing happens and no error is put out

## Tasks

- [x] Ensure report title follows contribution rules
- [x] Delete non-applicable description
- [x] I would like to work on a fix for this bug

**Comment by daniellanner** [comment]
The SnowFS executable is currently not notarized. This is a blocker until build pipeline of https://github.com/Snowtrack/SnowFS has been adjusted.

Current version to be notarized manually. ⌚

**Comment by daniellanner** [comment]
Updated debug output and receive the following:

```
ApplicationName='/Users/daniellanner/Documents/git/snowfs-for-unity/Assets/SnowFS for Unity/Plugins/Editor/bin/macos/snow', CommandLine='init .', CurrentDirectory='/Users/daniellanner/Documents/git/snowfs-for-unity/Assets', Native error= mono-io-layer-error (5)
  at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x002dc] in <aa976c2104104b7ca9e1785715722c9d>:0 
  at System.Diagnostics.Process.Start () [0x0003a] in <aa976c2104104b7ca9e1785715722c9d>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at SnowUnity.SnowCLI+<>cDisplayClass34_0.<ExecuteCommand>b0 () [0x00000] in /Users/daniellanner/Documents/git/snowfs-for-unity/Assets/SnowFS for Unity/Plugins/Editor/SnowCLI.cs:435
```
