### ISSUE TITLE
Filter versions in History panel by tags

### ISSUE THREAD

**Issue by daniellanner** [daniellanner/snowfs-for-unity#5]
# Filter versions by tags

Expose an option to filter versions by tags. Tags should be listed and selectable above the *History* panel.

- SnowFS for Unity v0.9.1

## Description

*SnowFS for Unity* offers the option to tag commits with emojis. This feature is useful for visually categorizing commits. It would be useful to actively filter versions in the History panel by toggling available tags in the versions.

## Proposed Solution

When looking for versions I want an option to filter for specific tags. This helps to narrow the search to versions of a specific type.

### As opposed to

Tags in *SnowFS for Unity* are not "tags" as implemented in Unity entities. A version can have multiple tags.

## Current workarounds

Scrolling and manually and visually identifying the version of interest.

## Tasks

- [ ] Ensure the request title follows contribution rules
- [ ] Delete non-applicable description
- [ ] I would like to work on this feature
