### ISSUE TITLE
:bug: (Add title for bug report)

### ISSUE THREAD

**Issue by cicada-dispatch** [daniellanner/snowfs-for-unity#9]
# (Add title for bug report)

(1-2 sentences what this bug is about.)
- Unity 2020.3.14f1

## Description

(A detailed summary of the unexpected behaviour.)
### Expected Behaviour

(A clear and concise description of what you expected to happen.)
## SnowFS Log file

```txt
1625619643375 +0500 $> init: initialized at D:/git/snowfs-for-unity/Assets
1625619654152 +0500 $> commit: Created Project
```

## Tasks

- [ ] Ensure report title follows contribution rules
- [ ] Delete non-applicable description
- [ ] I would like to work on a fix for this bug
